#!/usr/bin/env python3
"""
Generate the metadata snapshot + manifest for the MetadataUpdater pipeline.

This tool:
1. Reads the extracted regions.json (from extract_metadata.py)
2. Emits a compact JSON snapshot (lib/src/data/regions_data.dart format)
3. Computes SHA-256
4. Writes manifest.json with version, sha256, and download URL

Usage:
  python3 tool/gen_manifest.py --version 2026.08 --url-base https://cdn.example.com/mobile-num-metadata
"""

import argparse
import hashlib
import json
import sys
from pathlib import Path

REGIONS_JSON = Path("tools/data/regions.json")
SNAPSHOT_OUT = Path("lib/src/data/regions_data.dart")
MANIFEST_OUT = Path("tools/data/manifest.json")


def load_regions():
    if not REGIONS_JSON.exists():
        sys.exit(f"Missing {REGIONS_JSON}. Run extract_metadata.py first.")
    return json.loads(REGIONS_JSON.read_text())


def to_dart_data(regions):
    """Convert regions list to the Dart constant format."""
    return json.dumps(regions, separators=(",", ":"))


def write_snapshot(regions, version):
    """Write the Dart file with the embedded JSON + version constant."""
    json_str = to_dart_data(regions)
    # Use raw string literal to avoid escaping issues (same as gen_dart_data.py)
    content = (
        f"// GENERATED by tool/gen_manifest.py \u2014 DO NOT EDIT\n"
        f"// Metadata version: {version}\n"
        f"// Source: libphonenumber PhoneNumberMetadata.xml (Apache-2.0)\n\n"
        f"library;\n\n"
        f"/// JSON string containing all region metadata.\n"
        f"/// Decode with: `jsonDecode(kRegionsJson) as List<dynamic>`\n"
        f"const String kRegionsJson = r'''{json_str}''';\n\n"
        f"/// Embedded metadata version. Must match the manifest version.\n"
        f"const String kMetadataVersion = '{version}';\n"
    )
    SNAPSHOT_OUT.write_text(content)
    print(f"Wrote {SNAPSHOT_OUT} ({len(json_str)} bytes JSON)")


def write_manifest(regions, version, url_base):
    """Write manifest.json with SHA-256 and download URL."""
    json_bytes = to_dart_data(regions).encode("utf-8")
    sha256 = hashlib.sha256(json_bytes).hexdigest()

    manifest = {
        "version": version,
        "sha256": sha256,
        "url": f"{url_base.rstrip('/')}/regions-{version}.json",
    }
    MANIFEST_OUT.write_text(json.dumps(manifest, indent=2))
    print(f"Wrote {MANIFEST_OUT} (sha256={sha256[:16]}...)")

    # Also write the snapshot file that the manifest URL points to
    snapshot_file = Path(f"tools/data/regions-{version}.json")
    snapshot_file.write_text(to_dart_data(regions))
    print(f"Wrote {snapshot_file} (host this at {manifest['url']})")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True, help="Metadata version (e.g. 2026.08)")
    ap.add_argument("--url-base", required=True, help="Base URL for hosting snapshots (e.g. https://cdn.example.com/mobile-num-metadata)")
    args = ap.parse_args()

    regions = load_regions()
    write_snapshot(regions, args.version)
    write_manifest(regions, args.version, args.url_base)
    print(f"\nDone. Next release: bump pubspec version, publish, host {MANIFEST_OUT.name} and regions-{args.version}.json at your CDN.")


if __name__ == "__main__":
    main()